FROM node:22-bullseye-slim AS development

RUN apt-get update -qq && apt-get install -y -qq wget ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json turbo.json ./
COPY apps/api/package*.json apps/api/tsconfig*.json apps/api/nest-cli.json ./apps/api/
COPY packages/shared/package*.json packages/shared/tsconfig*.json ./packages/shared/

RUN npm install --no-package-lock

COPY apps/api/prisma ./apps/api/prisma
RUN cd apps/api && npx prisma generate

COPY apps/api/src ./apps/api/src
COPY packages/shared/src ./packages/shared/src

EXPOSE 3001

CMD ["npm", "run", "dev"]

FROM node:22-bullseye-slim AS production

WORKDIR /app

RUN apt-get update -qq && apt-get install -y -qq ca-certificates && rm -rf /var/lib/apt/lists/*

COPY package*.json turbo.json ./
COPY apps/api/package*.json apps/api/tsconfig*.json apps/api/nest-cli.json ./apps/api/
COPY packages/shared/package*.json packages/shared/tsconfig*.json ./packages/shared/

RUN npm install --no-package-lock

COPY apps/api/src ./apps/api/src
COPY packages/shared/src ./packages/shared/src

COPY apps/api/prisma ./apps/api/prisma
RUN cd apps/api && npx prisma generate && npm run build

COPY apps/api/dist ./apps/api/dist
COPY packages/shared/src ./packages/shared/src

EXPOSE 3001

CMD ["node", "apps/api/dist/main"]
