export enum LeadStatus {
  NEW = 'NEW',
  CONTACTED = 'CONTACTED',
  QUALIFYING = 'QUALIFYING',
  QUALIFIED = 'QUALIFIED',
  UNQUALIFIED = 'UNQUALIFIED',
  CONVERTED = 'CONVERTED',
  LOST = 'LOST',
}

export enum CustomerStatus {
  ACTIVE = 'ACTIVE',
  ONBOARDING = 'ONBOARDING',
  FOLLOW_UP = 'FOLLOW_UP',
  RENEWAL = 'RENEWAL',
  INACTIVE = 'INACTIVE',
  CHURNED = 'CHURNED',
}

export enum PipelineStageType {
  NEW_LEAD = 'NEW_LEAD',
  CONTACT_INITIATED = 'CONTACT_INITIATED',
  QUALIFYING = 'QUALIFYING',
  EVALUATION_SCHEDULED = 'EVALUATION_SCHEDULED',
  EVALUATION_DONE = 'EVALUATION_DONE',
  PROPOSAL_SENT = 'PROPOSAL_SENT',
  DECISION = 'DECISION',
  ACTIVE = 'ACTIVE',
  FOLLOW_UP = 'FOLLOW_UP',
  RENEWAL = 'RENEWAL',
  INACTIVE = 'INACTIVE',
  LOST = 'LOST',
}

export enum ConversationChannel {
  WHATSAPP = 'WHATSAPP',
  VOICE = 'VOICE',
  EMAIL = 'EMAIL',
  CHAT = 'CHAT',
  APP = 'APP',
}

export enum MessageRole {
  AI = 'AI',
  HUMAN = 'HUMAN',
  SYSTEM = 'SYSTEM',
  USER = 'USER',
}

export enum CallDirection {
  INBOUND = 'INBOUND',
  OUTBOUND = 'OUTBOUND',
}

export enum CallStatus {
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  NO_ANSWER = 'NO_ANSWER',
  BUSY = 'BUSY',
  CANCELLED = 'CANCELLED',
}

export enum TaskStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum TaskPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum AppointmentStatus {
  SCHEDULED = 'SCHEDULED',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
  RESCHEDULED = 'RESCHEDULED',
}

export enum CheckInStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  COMPLETED = 'COMPLETED',
  SKIPPED = 'SKIPPED',
  OVERDUE = 'OVERDUE',
}

export enum CheckInChannel {
  WHATSAPP = 'WHATSAPP',
  APP = 'APP',
  VOICE = 'VOICE',
  EMAIL = 'EMAIL',
}

export enum AlertLevel {
  NORMAL = 'NORMAL',
  ATTENTION = 'ATTENTION',
  PRIORITY = 'PRIORITY',
  URGENT = 'URGENT',
}

export enum AlertType {
  CHURN_RISK = 'CHURN_RISK',
  NO_SHOW = 'NO_SHOW',
  LOW_ADHERENCE = 'LOW_ADHERENCE',
  NEGATIVE_FEEDBACK = 'NEGATIVE_FEEDBACK',
  CHECK_IN_MISSED = 'CHECK_IN_MISSED',
  AUTOMATION_FAILURE = 'AUTOMATION_FAILURE',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  CONSENT_EXPIRED = 'CONSENT_EXPIRED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
}

export enum ConsentType {
  COMMUNICATION = 'COMMUNICATION',
  DATA_PROCESSING = 'DATA_PROCESSING',
  CALL_RECORDING = 'CALL_RECORDING',
  HEALTH_DATA = 'HEALTH_DATA',
  MARKETING = 'MARKETING',
  TERMS_OF_SERVICE = 'TERMS_OF_SERVICE',
}

export enum WorkflowTriggerType {
  LEAD_CREATED = 'LEAD_CREATED',
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  MESSAGE_UNANSWERED = 'MESSAGE_UNANSWERED',
  CALL_COMPLETED = 'CALL_COMPLETED',
  CALL_MISSED = 'CALL_MISSED',
  APPOINTMENT_CREATED = 'APPOINTMENT_CREATED',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_NO_SHOW = 'APPOINTMENT_NO_SHOW',
  PROPOSAL_SENT = 'PROPOSAL_SENT',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  CHECK_IN_COMPLETED = 'CHECK_IN_COMPLETED',
  CHECK_IN_MISSED = 'CHECK_IN_MISSED',
  ALERT_CREATED = 'ALERT_CREATED',
  CUSTOMER_INACTIVE = 'CUSTOMER_INACTIVE',
  RENEWAL_APPROACHING = 'RENEWAL_APPROACHING',
  STAGE_CHANGED = 'STAGE_CHANGED',
  SCHEDULED = 'SCHEDULED',
}

export enum WorkflowActionType {
  SEND_WHATSAPP = 'SEND_WHATSAPP',
  SEND_EMAIL = 'SEND_EMAIL',
  MAKE_CALL = 'MAKE_CALL',
  CREATE_TASK = 'CREATE_TASK',
  CHANGE_STAGE = 'CHANGE_STAGE',
  ASSIGN_USER = 'ASSIGN_USER',
  ADD_TAG = 'ADD_TAG',
  CREATE_ALERT = 'CREATE_ALERT',
  SCHEDULE_FOLLOW_UP = 'SCHEDULE_FOLLOW_UP',
  SEND_NOTIFICATION = 'SEND_NOTIFICATION',
  UPDATE_FIELD = 'UPDATE_FIELD',
  CALL_WEBHOOK = 'CALL_WEBHOOK',
  REQUEST_HUMAN_INTERVENTION = 'REQUEST_HUMAN_INTERVENTION',
}

export enum NotificationChannel {
  WHATSAPP = 'WHATSAPP',
  EMAIL = 'EMAIL',
  APP = 'APP',
  SMS = 'SMS',
}

export enum SubscriptionStatus {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  TRIAL = 'TRIAL',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  CANCELLED = 'CANCELLED',
}

export enum DocumentType {
  CONSENT_FORM = 'CONSENT_FORM',
  CONTRACT = 'CONTRACT',
  MEDICAL_RELEASE = 'MEDICAL_RELEASE',
  REPORT = 'REPORT',
  PRESCRIPTION = 'PRESCRIPTION',
  OTHER = 'OTHER',
}

export enum LeadSource {
  WEBSITE = 'WEBSITE',
  LANDING_PAGE = 'LANDING_PAGE',
  FORM = 'FORM',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  AD = 'AD',
  REFERRAL = 'REFERRAL',
  WHATSAPP = 'WHATSAPP',
  CALL = 'CALL',
  EVENT = 'EVENT',
  PARTNER = 'PARTNER',
  EMAIL = 'EMAIL',
  OTHER = 'OTHER',
}

export enum UserRole {
  ADMIN = 'ADMIN',
  SALES = 'SALES',
  PROFESSIONAL = 'PROFESSIONAL',
  SUPPORT = 'SUPPORT',
  MANAGER = 'MANAGER',
  CLIENT = 'CLIENT',
  AUDITOR = 'AUDITOR',
}
